# /manifests/script-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtester
  template:
    metadata:
      labels:
        app: loadtester
    spec:
      containers:
      - name: loadtester
        image: loadtester:latest
        imagePullPolicy: Never

