name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Train model
      run: |
        cd "Niveles/4/api"
        python train_model.py

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push API image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/api-fastapi:latest ./Niveles/4/api
        docker push ${{ secrets.DOCKER_USERNAME }}/api-fastapi:latest

    - name: Build and push LoadTester image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/loadtester:latest ./Niveles/4/loadtester
        docker push ${{ secrets.DOCKER_USERNAME }}/loadtester:latest
